# Generated by Django 5.0.6 on 2024-05-24 10:03

import auta.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vyrobce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte název výrobce', max_length=100, verbose_name='Název')),
                ('telefon', models.CharField(help_text='Zadejte telefonní číslo výrobce (včetně předvolby)', max_length=20, validators=[django.core.validators.RegexValidator(message='Zadejte prosím platné telefonní číslo.', regex='^(\\+420)? ?[1-9][0-9]{2}( ?[0-9]{3}){2}$')], verbose_name='Telefon')),
                ('email', models.EmailField(help_text='Zadejte e-mailovou adresu výrobce', max_length=254, validators=[django.core.validators.EmailValidator('Neplatný e-mail.')], verbose_name='E-mail')),
                ('logo', models.ImageField(blank=True, help_text='Nahrajte logo výrobce', null=True, upload_to=auta.models.Vyrobce.logo_upload_path, verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Výrobce',
                'verbose_name_plural': 'Výrobci',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='VyrobniZavod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte název výrobního závodu', max_length=100, verbose_name='Název')),
                ('adresa', models.CharField(help_text='Zadejte adresu výrobního závodu', max_length=200, verbose_name='Adresa')),
                ('vyrobce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auta.vyrobce', verbose_name='Výrobce')),
            ],
            options={
                'verbose_name': 'Výrobní závod',
                'verbose_name_plural': 'Výrobní závody',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('brabus 500', 'Brabus 500'), ('brabus 800', 'Brabus 800'), ('brabus 900', 'Brabus 900'), ('mercedes G63', 'Mercedes G63'), ('mercedes G65', 'Mercedes G65'), ('mercedes-AMG EQE', 'Mercedes-AMG EQE')], default='Brabus 900', max_length=45, verbose_name='Typ modelu')),
                ('spz', models.CharField(help_text='SPZ', max_length=8, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{8}$')], verbose_name='SPZ')),
                ('rok_vyroby', models.PositiveSmallIntegerField(blank=True, help_text='Zadej rok výroby', null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2024)], verbose_name='Rok výroby')),
                ('prevodovka', models.CharField(choices=[('manuální', 'Manuální'), ('automatická', 'Automatická')], default='manuální', max_length=15, verbose_name='Typ převodovky')),
                ('palivo', models.CharField(choices=[('benzín', 'Benzín'), ('nafta', 'Nafta'), ('elektrika', 'Elektrika')], default='benzín', max_length=10, verbose_name='Typ paliva')),
                ('zavod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auta.vyrobnizavod', verbose_name='Výrobní závod')),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Auta',
                'ordering': ['zavod', '-rok_vyroby'],
            },
        ),
    ]
